# Generated by Django 4.0.6 on 2022-12-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_img',
            field=models.ImageField(default='memo-black-bg.png', upload_to='user_images'),
        ),
    ]
