# Generated by Django 4.0.6 on 2023-01-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_profile_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile',
            field=models.CharField(default='U', max_length=3),
        ),
    ]
